---
repos:
  - repo: https://github.com/dadav/helm-schema
    rev: 0.18.1
    hooks:
      - id: helm-schema
        args:
          - "--dependencies-filter=generic-app"
          - "--skip-auto-generation=additionalProperties"
          - "--append-newline"
