{{- range $d := .Values.deployments }}
{{- if $d.ingress }}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-{{ $d.name }}
  namespace: {{ template "app.namespace" $ | default "default" }}
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "{{ regexReplaceAll `\..*` $d.ingress.domain `` }}-letsencrypt-prod"

spec:
  ingressClassName: traefik
  tls:
    - hosts: ["{{ if $d.ingress.subdomain }}{{ $d.ingress.subdomain }}.{{ end }}{{$d.ingress.domain}}"]
      secretName: {{ $d.name }}-tls
  rules:
    - host: "{{ if $d.ingress.subdomain }}{{ $d.ingress.subdomain }}.{{ end }}{{$d.ingress.domain}}"
      http:
        paths:
          - path: {{ $d.ingress.urlPrefix | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: service-{{ $d.name }}
                port:
                  number: {{ $d.service.port | default 80 }}
{{- end }}
---
{{- end }}
