{{- range (concat .Values.deployments .Values.statefulSets) }}
{{- if .secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: secrets-{{ .name }}
  namespace: {{ template "app.namespace" $ | default "default" }}
type: Opaque
stringData: {{ .secrets | toYaml | nindent 2 }}
{{- end }}
---
{{- end }}
