{{- range (concat .Values.deployments .Values.statefulSets) }}
{{- if .service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ template "app.namespace" $ | default "default" }}
  labels:
    app: {{ .name }}
spec:
  type: {{ .service.type | default "ClusterIP" }}
  {{- if .service.headless }}
  clusterIP: None
  {{- end }}
  ports:
    - port: {{ .service.port | default 80 }}
      targetPort: {{ .containerPort | default .service.port | default 80 }}
      protocol: {{ .service.protocol | default "TCP" }}
  selector:
    app: {{ .name }}
{{- end }}
---
{{- end }}
