# yaml-language-server: $schema=values.schema.json
application:
  version: "not set"
  # image:
  port: 80
  # environment:
  # secrets:
  # volume:
  #   size:
  #   mountPath:
ingress:
  # - subdomain: "app"
  #   urlPrefix: "/"
