apiVersion: v1
kind: Service
metadata:
  name: {{- template "app.service" . }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: app-port
  selector:
    app: {{- template "app.service" . }}
