{{- if .Values.application.volumes }}
{{- range .Values.application.volumes }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: {{ .size }}
---
{{- end }}
{{- end }}
