{{- range .Values.deployments }}
{{- if .secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: secrets-{{ .name }}-{{ $.Values.environment }}
  namespace: {{ template "app.namespace" $ | default "default" }}
type: Opaque
stringData: {{ .secrets | toYaml | nindent 2 }}
{{- end }}
---
{{- end }}
