{{- range .Values.deployments }}
{{- if .exposeService }}
apiVersion: v1
kind: Service
metadata:
  name: service-{{ .name }}-{{ $.Values.environment }}
  namespace: {{ template "app.namespace" $ | default "default" }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: app-port
  selector:
    app: {{ .name }}
---
{{- end }}
{{- end }}
